### PR TITLE
Have Quark Module actually use Alex's Caves ancient_leaves

### PR DESCRIPTION
**Pull request by VoidLeech**
### Issues Fixed
- The ancient_leaves from Alex's Caves didn't generate the hedge or leaf_pile blocks from the quark module. This is because quark's Ashen leaves have the ancient_leaves id, so this triggered the isAlreadyRegistered check.

### CODE REVIEW

**Comment by Xelbayria** [comment]
I can take care of this. 

**UPDATE:**
DONE!
So the reason is that Alex's Caves ancient_leaves shouldn't be discarded, right?

**Comment by Xelbayria** [comment]
oh I need the full ID of ancient_leaves from alexscave

**Comment by VoidLeech** [comment]
Ah there’s a better place for it (: 
The full id is alexscaves:ancient_leaves

**Comment by Xelbayria** [comment]
👍🏻 

yes there is a better place for it. and it's in `isLeavesBlockAlreadyRegistered` via HardedBlockType class

and the code is this `if (modId.equals("quark") && leaveTypeID.equals("alexscave:ancient")) return false;`

I need to check Moonlight Lib to see if the leaves has the woodType blc i know Quark's hedge required 2 things: leaves and a log.

**Comment by VoidLeech** [comment]
Hedges do use oak logs as default so as long as the leaves get detected it’s good. But also if it’s not I do have it included in my pr (to moonlight) because it uses jungle logs instead of a new wood.

**Comment by Xelbayria** [comment]
> Hedges do use oak logs as default so as long as the leaves get detected it’s good. But also if it’s not I do have it included in my pr (to moonlight) because it uses jungle logs instead of a new wood.

its Log is jungle_log, 👍🏻, I'll check and take care of it.

**Pull request closed without merging**
