### PR TITLE
[1.19.2] Boatload support

### PR DESCRIPTION
**Pull request by Tkain**
This PR aims to add support for the boats added by the mod [Boatload](https://www.curseforge.com/minecraft/mc-mods/boatload), which adds vanilla boats (boats and boats /w chests) for vanilla wood types without them as well as custom boats (boats /w furnaces and large boats) for all vanilla wood types. This PR adds support for Boatload by adding a (Forge-only) module for Boatload to the mod that handles creating both vanilla's and Boatload's boats for wood types detected by Wood Good.

At the moment, this PR is drafted because of a few lingering issues:

- Recipes are currently a bit wonky; some aren't generated at all and others use incorrect boats. I'm still looking into how this occurs.
- The Boatload module creates vanilla boats for mods that already have vanilla boats. I'm still thinking over how to best detect when this is the case; with how the mod is currently structured, we can't check the item registry at the time of creating our boats.
- Boats' icons look a bit washed out; I'd like to have them match vanilla boats' more contrasted colors if possible, but I'm not sure how to do that without affecting the boats themselves.

### CODE REVIEW

**Comment by MehVahdJukaar** [comment]
so for the recipe there is an ongoing bug that has been reported on supplementaries too as it uses same system. somehow the BlockType.changeItemType is failing resulting in many recipes with same input (oak sign) for different outputs. Thing is i havent been able to replicate this in dev once. If this is indeed the same issue might give me a clue onto what could be wrong with it but i believe its down to how childs are filled for wood types. As for the item issue yeah that's indeed an issue, i didnt really made this system to work for anything that is not block based. a solutuon could be to alter code in moonlight to do what is done for blocks for items aswell but that stuff is very convoluted and complex as its tbh quite hacky onto how it works but thats the price to pay for dynamic registration

**Comment by MehVahdJukaar** [comment]
irnonically fabric system would have supported this but im doing stuff too early on forge

**Comment by Tkain** [comment]
I'm guessing that most of these issues would need to be solved in Moonlight rather than WoodGood, then?

**Comment by MehVahdJukaar** [comment]
yeah. Complicated tho. A quick and easy solution would be to just register for all wood types minus vanilla ones minus a hardcoded list from some known mods that do add these

**Comment by Xelbayria** [comment]
@Tkain 
Is it alright if I take care of this **Boatload** and finish it?

**Comment by Tkain** [comment]
> this **Boatload**

_(GROAN)_

But sure, go ahead! You can fork my repo and then PR your changes either to my repo or directly to the main repo if you want.

The only thing you'd need to do to make this feature-complete is to find a way to disable generating the vanilla boats (through Blueprint) for mods whose wood types already implement them. The only reason I haven't done this is because I think it may involve hardcoding a list of mod IDs that implement their own boats (which is not only a bit ugly, but also something that involves testing that I don't have the patience for).

**Comment by Xelbayria** [comment]
> > this **Boatload**
> 
> _(GROAN)_
> 
> But sure, go ahead! You can fork my repo and then PR your changes either to my repo or directly to the main repo if you want.
> 
> The only thing you'd need to do to make this feature-complete is to find a way to disable generating the vanilla boats (through Blueprint) for mods whose wood types already implement them. The only reason I haven't done this is because I think it may involve hardcoding a list of mod IDs that implement their own boats (which is not only a bit ugly, but also something that involves testing that I don't have the patience for).

Thanks for the replying. the way you reacted to "Boatload". so it's that bad? I'll see what I can do on my side and thanks for the details. that is a helpful info to have.

**Comment by Tkain** [comment]
> the way you reacted to "Boatload". so it's that bad?

No, I was just making a joke about the corny nature of your pun. The mod isn't difficult to work with, if that's what you meant.

**Comment by Xelbayria** [comment]
BoatLoad is added to EveryComp. this is no longer needed. Closing this.

**Pull request closed without merging**
