### PR TITLE
Building But Better module (Fabric, Forge)

### PR DESCRIPTION
**Pull request by wiidotmom**
https://modrinth.com/mod/building-but-better

Should be fairly simple, all of the textures use the planks palette as far as I can tell

Todo:
- [x] Layers
- [x] Trims
- [x] Beams
- [x] Beam Stairs
- [x] Beam Slabs
- [x] Supports
- [x] Frames
- [x] Pallets
- [x] Lanterns
- [x] Ladders
- [x] Walls
- [x] Fabric module (Building But Better uses separate codebases for Fabric & Forge)

### CODE REVIEW

**Comment by Xelbayria** [comment]
Just checking, Are the source code for FORGE and FABRIC different? If yes, then all is good.

**Comment by wiidotmom** [comment]
Yes, unfortunately
https://github.com/starfish-studios/Building-But-Better/tree/main
https://github.com/starfish-studios/Building-But-Better/tree/forge

**Comment by Xelbayria** [comment]
Alright. thanks for adding **Building But Better Module**.

**Comment by Xelbayria** [comment]
Let me know if you don't time to finish the rest. I can finish the rest.

**Comment by Xelbayria** [comment]
I haven't heard from you. I'll finish the rest of the module.

**Comment by Xelbayria** [comment]
Since I've not heard from you for a while.  Just so you know. I copied your files into my IDE and you have done a good job. I've finished the rest of the work. **Building But Better** will be included in v2.6.74. Thanks for creating the module.

**Pull request closed without merging**
